# Site settings
description: Unofficial Waze Developer Community
baseurl: "/cards-jekyll-template" # the subpath of your site, e.g. /blog
url: "https://wazers.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Wazers
user_description: Unofficial Waze Developer Community
user_title: Waze Developer Community
email: anon@anon.com
twitter_username: wazedev
github_username:  wazers
gplus_username:  115976708093729381066
disqus_username: wazers

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
